spring:
  application:
    name: frotaPro
  profiles:
    active: dev

  jackson:
    mapper:
      accept-case-insensitive-enums: true

  kafka:
    consumer:
      group-id: frota-pro-api-v2
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "br.com.frotasPro.api.integracao.dto,br.com.frotasPro.integradora.winthor.dto"
        spring.json.use.type.headers: false

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  error:
    include-message: always

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: always

frotapro:
  empresa-sync-id: 11111111-2222-3333-4444-555555555555
  kafka:
    topics:
      carga-sync-request: frotapro.carga.sync.request
      carga-sync-response: frotapro.carga.sync.response
      motorista-sync-request: frotapro.motorista.sync.request
      motorista-sync-response: frotapro.motorista.sync.response
      caminhao-sync-request: frotapro.caminhao.sync.request
      caminhao-sync-response: frotapro.caminhao.sync.response


jwt:
  public:
    key: classpath:authz.pub
  private:
    key: classpath:authz.pem